### ISSUE TITLE
Feat : 마이페이지 설계

### ISSUE THREAD

**Issue by ungpyolee** [OZ-Coding-School/oz_03_main-003-FE#38]
## 어떤 기능인가요?

> 마이페이지 유저 정보 렌더링 및 CRUD

## 작업 상세 내용

-   [x] 유저 정보 페이지
-   [x] 유저 정보 수정 페이지
-   [x] 회원 탈퇴 기능

**Comment by yoyobar** [comment]
초안 설계 완료
